# Generated by Django 4.1.2 on 2022-10-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservicio', '0003_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
