# Generated by Django 4.1.2 on 2022-10-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservicio', '0004_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Servicios'),
        ),
    ]
