# Generated by Django 4.1.2 on 2022-10-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservicio', '0006_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
